version: '0.1'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  poke-draft-bot:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      TOKEN=${TOKEN}
      PERMISSIONS=${PERMISSIONS}
    command: ["python", "./pokedraftbot/bot.py"]

volumes:
  db_data:
    
